// Shared prompt instruction for weighing a student's reported English
// proficiency test (IELTS, TOEFL iBT, Duolingo English Test, PTE Academic,
// Cambridge English Scale — see lib/standardized-tests.ts) against typical
// requirements, which genuinely differ by country. There's no per-school
// published English-test threshold in this app's catalog (unlike SAT/ACT
// ranges), so this is explicitly framed as general, typical guidance the AI
// reasons from — never presented as a specific school's real policy unless
// that's already stated in the school's own listed requirements.
export const ENGLISH_TEST_GUIDANCE = `When the student has reported an English proficiency test score, weigh whether it's likely comfortable, borderline, or short of what's typically expected for admission to THIS school's country — these norms genuinely differ by country, so don't apply one universal bar. As general (not school-specific) guidance: competitive US and UK programs commonly expect IELTS ~6.5-7.5 or TOEFL iBT ~90-110; Australia commonly asks for IELTS ~6.5+; Singapore and Hong Kong programs vary but commonly sit around IELTS ~6.0-6.5+; English-taught programs in Germany and France often expect IELTS ~6.0-6.5 or TOEFL iBT ~80+. Convert the student's reported test (whichever of IELTS/TOEFL/Duolingo/PTE/Cambridge they gave) to the same rough tier using well-known public equivalency tables, don't just compare raw numbers across different tests. If this school's own listed requirements already state a specific English-test threshold, use that instead and say so directly — otherwise present this only as typical/general context, never as this school's actual published cutoff. If the score looks comfortably strong for this country, mention it as a genuine strength; if it looks borderline or short, flag it as a specific weakness/action step (e.g. "your IELTS 6.0 is on the low side for competitive UK programs, which often want 6.5-7.0 — a retake could help"). If no English test was reported at all, don't penalize the student for it unless a requirement above explicitly calls for one — just skip this point silently.`
